/**
 * Centralized mock data for development and testing.
 *
 * All mock data lives here so it can be swapped for real API calls in one
 * place. The travel bucket list theme provides realistic sample data for
 * trips, destinations, and trip tasks.
 */

import type { Trip, Destination, TripTask, DashboardSummary } from '@/types'

// ---------------------------------------------------------------------------
// Trips — 8 trips across continents with varied statuses and budgets
// ---------------------------------------------------------------------------

export const mockTrips: Trip[] = [
  {
    id: 'trip-001',
    name: 'Tokyo & Kyoto Explorer',
    description: 'Two-week journey through Japan — temples, street food, and cherry blossoms.',
    status: 'Booked',
    priority: 'Bucket List',
    budget: 5500,
    startDate: '2026-04-01',
    endDate: '2026-04-14',
    country: 'Japan',
    continent: 'Asia',
  },
  {
    id: 'trip-002',
    name: 'Greek Island Hopping',
    description: 'Santorini, Mykonos, and Crete — sun, sea, and ancient ruins.',
    status: 'Planning',
    priority: 'High',
    budget: 4200,
    startDate: '2026-06-15',
    endDate: '2026-06-28',
    country: 'Greece',
    continent: 'Europe',
  },
  {
    id: 'trip-003',
    name: 'Patagonia Trek',
    description:
      'Hiking Torres del Paine and the Perito Moreno glacier — bucket list adventure in southern Argentina.',
    status: 'Dreaming',
    priority: 'Bucket List',
    budget: 6800,
    startDate: '2027-01-10',
    endDate: null,
    country: 'Argentina',
    continent: 'South America',
  },
  {
    id: 'trip-004',
    name: 'NYC Weekend Getaway',
    description: 'Broadway shows, Central Park, and pizza crawl through Brooklyn.',
    status: 'Completed',
    priority: 'Medium',
    budget: 2200,
    startDate: '2025-11-08',
    endDate: '2025-11-11',
    country: 'USA',
    continent: 'North America',
  },
  {
    id: 'trip-005',
    name: 'Kenya Safari',
    description: 'Masai Mara wildlife safari with hot air balloon ride over the savanna.',
    status: 'Planning',
    priority: 'High',
    budget: 7500,
    startDate: '2026-08-20',
    endDate: '2026-08-30',
    country: 'Kenya',
    continent: 'Africa',
  },
  {
    id: 'trip-006',
    name: 'Bali Retreat',
    description: 'Yoga, rice terraces, and temple visits in Ubud and Seminyak.',
    status: 'Booked',
    priority: 'Medium',
    budget: 3100,
    startDate: '2026-05-05',
    endDate: '2026-05-15',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    id: 'trip-007',
    name: 'Iceland Ring Road',
    description: 'Drive the Ring Road — waterfalls, geysers, Northern Lights, and black sand beaches.',
    status: 'Dreaming',
    priority: 'Bucket List',
    budget: 5000,
    startDate: '2026-10-01',
    endDate: null,
    country: 'Iceland',
    continent: 'Europe',
  },
  {
    id: 'trip-008',
    name: 'Great Barrier Reef Dive',
    description: 'Scuba diving and snorkelling the Great Barrier Reef — marine life paradise.',
    status: 'Cancelled',
    priority: 'Low',
    budget: 0,
    startDate: '2025-12-01',
    endDate: null,
    country: 'Australia',
    continent: 'Oceania',
  },
]

// ---------------------------------------------------------------------------
// Destinations — 10 destinations with type/season/cost variety
// ---------------------------------------------------------------------------

export const mockDestinations: Destination[] = [
  {
    id: 'dest-001',
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    type: 'Cultural',
    bestSeason: 'Spring',
    averageDailyCost: 150,
    isVisited: false,
  },
  {
    id: 'dest-002',
    name: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    type: 'Island',
    bestSeason: 'Summer',
    averageDailyCost: 200,
    isVisited: false,
  },
  {
    id: 'dest-003',
    name: 'Queenstown',
    country: 'New Zealand',
    continent: 'Oceania',
    type: 'Adventure',
    bestSeason: 'Winter',
    averageDailyCost: 180,
    isVisited: true,
  },
  {
    id: 'dest-004',
    name: 'Marrakech',
    country: 'Morocco',
    continent: 'Africa',
    type: 'Cultural',
    bestSeason: 'Spring',
    averageDailyCost: 80,
    isVisited: false,
  },
  {
    id: 'dest-005',
    name: 'Reykjavik',
    country: 'Iceland',
    continent: 'Europe',
    type: 'Adventure',
    bestSeason: 'Winter',
    averageDailyCost: 220,
    isVisited: false,
  },
  {
    id: 'dest-006',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    type: 'Beach',
    bestSeason: 'Summer',
    averageDailyCost: 70,
    isVisited: false,
  },
  {
    id: 'dest-007',
    name: 'Banff',
    country: 'Canada',
    continent: 'North America',
    type: 'Mountain',
    bestSeason: 'Summer',
    averageDailyCost: 160,
    isVisited: true,
  },
  {
    id: 'dest-008',
    name: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
    type: 'City',
    bestSeason: 'Spring',
    averageDailyCost: 100,
    isVisited: true,
  },
  {
    id: 'dest-009',
    name: 'Cusco',
    country: 'Peru',
    continent: 'South America',
    type: 'Cultural',
    bestSeason: 'Autumn',
    averageDailyCost: 60,
    isVisited: false,
  },
  {
    id: 'dest-010',
    name: 'Fiji',
    country: 'Fiji',
    continent: 'Oceania',
    type: 'Island',
    bestSeason: 'Year-round',
    averageDailyCost: 190,
    isVisited: false,
  },
]

// ---------------------------------------------------------------------------
// Trip Tasks — 12 tasks spread across statuses (3 per column)
// ---------------------------------------------------------------------------

export const mockTripTasks: TripTask[] = [
  {
    id: 'task-001',
    title: 'Research visa requirements for Japan',
    description: 'Check if tourist visa is needed and gather documentation requirements.',
    status: 'To Research',
    priority: 'High',
    tripId: 'trip-001',
    assignee: 'Emily Chen',
    dueDate: '2026-02-15',
    createdAt: '2026-01-10',
  },
  {
    id: 'task-002',
    title: 'Compare travel insurance providers',
    description: 'Get quotes from at least three providers covering adventure activities.',
    status: 'To Research',
    priority: 'Medium',
    tripId: 'trip-003',
    assignee: 'Liam Patel',
    dueDate: '2026-03-01',
    createdAt: '2026-01-12',
  },
  {
    id: 'task-003',
    title: 'Find best time to visit Masai Mara for migration',
    description: '',
    status: 'To Research',
    priority: 'Bucket List',
    tripId: 'trip-005',
    assignee: null,
    dueDate: null,
    createdAt: '2026-01-15',
  },
  {
    id: 'task-004',
    title: 'Book Tokyo to Kyoto bullet train tickets',
    description: 'Reserve Shinkansen seats — compare Japan Rail Pass vs individual tickets.',
    status: 'Booking',
    priority: 'High',
    tripId: 'trip-001',
    assignee: 'Emily Chen',
    dueDate: '2026-03-01',
    createdAt: '2026-01-08',
  },
  {
    id: 'task-005',
    title: 'Reserve Santorini cave hotel',
    description: 'Book caldera-view suite in Oia for 5 nights. Compare Booking.com vs direct.',
    status: 'Booking',
    priority: 'High',
    tripId: 'trip-002',
    assignee: 'Sophie Williams',
    dueDate: '2026-03-15',
    createdAt: '2026-01-20',
  },
  {
    id: 'task-006',
    title: 'Book Bali villa with pool',
    description: 'Find private villa in Ubud with infinity pool and rice field views.',
    status: 'Booking',
    priority: 'Medium',
    tripId: 'trip-006',
    assignee: 'Liam Patel',
    dueDate: '2026-03-20',
    createdAt: '2026-01-22',
  },
  {
    id: 'task-007',
    title: 'Confirm Tokyo hotel reservation',
    description: 'Shinjuku hotel confirmed for April 1-7. Confirmation #TK-2026-4412.',
    status: 'Confirmed',
    priority: 'High',
    tripId: 'trip-001',
    assignee: 'Emily Chen',
    dueDate: '2026-03-25',
    createdAt: '2026-01-05',
  },
  {
    id: 'task-008',
    title: 'Confirm safari lodge booking',
    description: 'Masai Mara lodge confirmed — 4 nights tented camp with game drives included.',
    status: 'Confirmed',
    priority: 'Bucket List',
    tripId: 'trip-005',
    assignee: 'Jane Doe',
    dueDate: '2026-06-01',
    createdAt: '2026-01-18',
  },
  {
    id: 'task-009',
    title: 'Confirm Bali return flights',
    description: 'Round-trip flights confirmed via Singapore Airlines. Ref: SQ-88742.',
    status: 'Confirmed',
    priority: 'Medium',
    tripId: 'trip-006',
    assignee: null,
    dueDate: null,
    createdAt: '2026-01-25',
  },
  {
    id: 'task-010',
    title: 'Pack for NYC trip',
    description: 'Winter clothes, comfortable walking shoes, Broadway outfit.',
    status: 'Done',
    priority: 'Low',
    tripId: 'trip-004',
    assignee: 'Jane Doe',
    dueDate: '2025-11-07',
    createdAt: '2025-10-20',
  },
  {
    id: 'task-011',
    title: 'Submit NYC expense report',
    description: 'Receipts collected and submitted. Total spend within budget.',
    status: 'Done',
    priority: 'Medium',
    tripId: 'trip-004',
    assignee: 'John Smith',
    dueDate: '2025-11-20',
    createdAt: '2025-11-12',
  },
  {
    id: 'task-012',
    title: 'Cancel Great Barrier Reef dive booking',
    description: 'Refund processed for cancelled dive trip. Confirmation email saved.',
    status: 'Done',
    priority: 'Low',
    tripId: 'trip-008',
    assignee: 'Megan Taylor',
    dueDate: null,
    createdAt: '2025-11-28',
  },
]

// ---------------------------------------------------------------------------
// Dashboard Summary — computed from mockTrips
// ---------------------------------------------------------------------------

export const mockDashboardSummary: DashboardSummary = {
  totalTrips: mockTrips.length,
  upcomingTrips: mockTrips.filter((t) => t.status === 'Booked' || t.status === 'Planning').length,
  totalBudget: mockTrips.reduce((sum, t) => sum + t.budget, 0),
  countriesVisited: mockTrips.filter((t) => t.status === 'Completed').length,
}
